### PR TITLE
Improved Dutch localization

### PR DESCRIPTION
**Pull request by bramschulting**
[This line](https://github.com/Instapaper/instapaper-iOS-localization/blob/0c7121ca17e716761635f7377cf25f3fa2817926/Dutch/Localizable.strings#L674) is still incorrect, but I'm not sure what you mean in English. If could explain me what it means, I can fix it too.

### CODE REVIEW

**Comment by Donohue** [comment]
Hey Bram,

This is looking pretty great. I do have a comment on your translation of "Archive". Are you using that as a verb or a noun? We have an "Archive" section that's a noun, and an "Archive" action which is a verb. Are these translations different in your language? I believe we switched from "Archief" to "Archiveer" on purpose.

I will merge once you clarify the above.

The line you are referring to is for Instapaper's built-in dictionary which is from [Wiktionary](http://www.wiktionary.org/). The best way I can rephrase it is...

"Instapaper's offline, built-in dictionary is generated from Wiktionary.com

It can link words in a definition to another definition in the dictionary, and support other dictionary apps."

The second line means if there's a dictionary entry lookup for "massive" that uses the word "large" in the definition, you can click on "large" to get the definition for "large".

Best,
Brian

**Comment by bramschulting** [comment]
About archief/archiveer: I think it's best if I give you a sentence
- I will archive (`archiveer`) the article.
- I will check my archive (`archief`).

So, `archiveer` is a verb (in I-form) and `archief` is a noun. That means that the sidebar and the 'action button' should have different translations.

**Comment by bramschulting** [comment]
Is it OK if I create a separate pull request for the other line? I need to finish something for school real quick. Should be done in an hour or so.

**Comment by Donohue** [comment]
Yes that's no problem, Bram!

**Pull request merged**
